# pandas / numpy

# Цель

Ознакомиться с функционалом основного инструментария анализа данных.

In [ ]:
# مكتبة Pandas هي أداة قوية وفعالة لمعالجة البيانات وتحليلها. تجعل التعامل مع البيانات الكبيرة والمعقدة أكثر سهولة وفعالية.
# يمكنك استخدامها لعمليات مثل تنظيف البيانات، دمجها، تحليلها، ورسمها

# Pandas is a Python library for data manipulation and analysis.
# It provides data structures and functions to efficiently handle and process large datasets, including:

# * Data cleaning and preprocessing
# * Data merging and joining
# * Data filtering and sorting
# * Data grouping and aggregation
# * Data reshaping and pivoting
# * Data visualization

# Pandas is particularly useful for working with structured data, such as tabular data, time series data, and financial data.
# It's often used in combination with other popular Python libraries, such as NumPy, Matplotlib, and Scikit-learn.

# pandas

https://pandas.pydata.org/

Быстрая работа с алгеброй это очень хорошо, однако задачи которые мы обычно пытаемся решить в реальной жизни не ограничиваются одними лишь числами. Обычно при работе с данными мы наблюдаем что каждый кусочек данных помимо числовых значений может относиться к разным категориям, быть логически отделимым от другого куcочка таких же данных по набору признаков يمكن فصلها منطقيًا عن جزء آخر من نفس البيانات بناءً على مجموعة من الميزات

Тут для анализа данных появляется такой инструмент как pandas. Он реализует работу с кусками данных. Тип объекта с данными который загружен с помощью pandas будет называтья DataFrame, а одна отдельная запись из датафрейма будет называться series.

Внутри себя pandas использует алгебру реализованную в NumPy. Собственно говоря, pandas имеет под собой зависимость в numpy. https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L28


В качестве упражнения с pandas будем использовать даные по ковиду.

Есть большой датафрейм по заболеванию, его можно отыскать здесь يمكن العثور عليها هنا:: https://github.com/DataRepo2019/Data-files/blob/master/COVID-19-geographic-disbtribution-worldwide-2020-06-29.xlsx

Есть небольшая вырезка по нему за один из дней, с которой мы и будем работать в первую очередь, она находится вот здесь: https://raw.githubusercontent.com/DataRepo2019/Data-files/master/subset-covid-data.csv

In [ ]:
# тип объекта с данными который загружен с помощью pandas будет называтья DataFrame
# а одна отдельная запись (один столбец) из датафрейма будет называться series

In [ ]:
import pandas as pd

data_frame_covid = pd.read_csv("https://raw.githubusercontent.com/DataRepo2019/Data-files/master/subset-covid-data.csv") #function read_csv takes links and files
data_frame_covid

,country,continent,date,day,month,year,cases,deaths,country_code,population
0,Afghanistan,Asia,2020-04-12,12,4,2020,34,3,AFG,37172386.0
1,Albania,Europe,2020-04-12,12,4,2020,17,0,ALB,2866376.0
2,Algeria,Africa,2020-04-12,12,4,2020,64,19,DZA,42228429.0
3,Andorra,Europe,2020-04-12,12,4,2020,21,2,AND,77006.0
4,Angola,Africa,2020-04-12,12,4,2020,0,0,AGO,30809762.0
...,...,...,...,...,...,...,...,...,...,...
201,Venezuela,America,2020-04-12,12,4,2020,0,0,VEN,28870195.0
202,Vietnam,Asia,2020-04-12,12,4,2020,4,0,VNM,95540395.0
203,Yemen,Asia,2020-04-12,12,4,2020,0,0,YEM,28498687.0
204,Zambia,Africa,2020-04-12,12,4,2020,0,0,ZMB,17351822.0
205,Zimbabwe,Africa,2020-04-12,12,4,2020,3,0,ZWE,14439018.0

In [ ]:
### all this is a dataframe? and one column of them is a series? right?

# Yes, what you have is a DataFrame, which is a two-dimensional, tabular data structure commonly used in data analysis,
# particularly with libraries like Pandas in Python.
# Each row represents a record (in this case, data for a specific country on a specific date),
# and each column represents a variable (like `country`, `continent`, `cases`, etc.).

# A Series, on the other hand, is a one-dimensional array-like structure that can hold data of any type.
# It can be thought of as a single column from a DataFrame. For instance,
# if you were to extract the `cases` column from your DataFrame, that would be a Series.

# So, to summarize:
# - The entire dataset you provided is a DataFrame.
# - Each individual column (like `cases` or `country`) can be considered a Series.

In [ ]:
# indexes = بالجدول السابق محطوطات عاليسار ومن 0 لل 205 لأن هوا عددهن 206

## основные термины при работе с pandas

Pandas вводит ряд новых слов которые будут использованы при работе с ней. Имеет смысл с ними ознакомиться.

*__Series__* (серия)- это одномерный, именованный (помеченный) массив إنها مصفوفة أحادية البعد، مسماة (مُسمَّاة), который может хранить данные любого типа, включая целые числа, числа с плавающей точкой, строки и объекты Python.

Базовая структура серии состоит из двух компонентов: данных и индекса.

В серии *__данные__* представляют собой одномерный массив NumPy, содержащий фактические значения данных.

In [ ]:
# just an example of series(here we will see lables and names)
data_frame_covid.T.iloc[:,0]

# explaining  ==>  https://chat.hix.ai/ar/share/cm0g2ntwx0gey5j0qaog0rkhq
# questions   ==>  https://chat.hix.ai/ar/share/cm0g2ze600gtjlze5nspwrude

country         Afghanistan
continent              Asia
date             2020-04-12
day                      12
month                     4
year                   2020
cases                    34
deaths                    3
country_code            AFG
population       37172386.0
Name: 0, dtype: object

In [ ]:
# Question 1:
# Given the following DataFrame that contains information about different fruits:


import pandas as pd

data = {
    'Fruit': ['Apple', 'Banana', 'Cherry'],
    'Color': ['Red', 'Yellow', 'Red'],
    'Price': [1.2, 0.5, 2.0]
}
df_fruits = pd.DataFrame(data)

# data

### What is the value in the first row of the 'Color' column after transposing the DataFrame?
first_color_value = df_fruits.T.iloc[1, 0]  # Accessing the first element of the 'Color' row
print(first_color_value)

Red

In [ ]:
# find the type of series
type(data_frame_covid.T.iloc[:,0])    # == pandas.core.series.Series

pandas.core.series.Series

*__Индекс__* - это структура, похожая на массив, которая помечает каждый элемент массива данных الذي يمثل كل عنصر من عناصر مجموعة البيانات. По умолчанию индекс представляет собой последовательность целых чисел, начинающуюся с нуля, но вы также можете предоставить пользовательские метки (Метка = label 🏷️ العلامة = التسمية) для индекса. Это облегчает обращение и манипулирование элементами данных на основе их меток.

Чтобы создать серию, вы можете использовать конструктор pd.Series () и передать список, словарь или массив NumPy в качестве данных. Вы также можете передать необязательный параметр индекса, чтобы указать пользовательские метки для элементов данных.

In [ ]:
data_frame_covid.index    # we used .index, looooook at the result

RangeIndex(start=0, stop=206, step=1)

In [ ]:
type(data_frame_covid.index)

pandas.core.indexes.range.RangeIndex

In [ ]:
data_frame_covid.index.tolist()[:10]    # https://chat.hix.ai/ar/share/cm0hwjyyi0in57jtiqki4yu57
                                        # https://chat.hix.ai/ar/share/cm0hwp1bo0v7z14d8lwd2jqfw

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# data_frame_covid.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205]

*__DataFrame__* (ДатаФрейм, Таблица данных) - это двумерная, изменяемая в размере и гетерогенная структура табличных данных с маркированными осями (строками и столбцами). Его можно рассматривать как коллекцию объектов Series, где каждый столбец представляет собой объект Series. DataFrames предназначены для обработки широкого спектра типов данных, что делает его универсальным и мощным инструментом для обработки и анализа данных. Базовая структура DataFrame состоит из трех компонентов: данных, индекса и столбцов.

В DataFrame данные хранятся в виде коллекции из одного или нескольких объектов Series, каждый столбец которых представляет собой отдельную Series. Данные в каждой Series могут быть различных типов, таких как целые числа, числа с плавающей точкой или строки.

In [ ]:
type(data_frame_covid)

pandas.core.frame.DataFrame

*__Столбцы__* являются структурой, подобной массиву, которая помещает метку на каждый столбец в DataFrame.

الأعمدة عبارة عن بنية تشبه المصفوفه تضع تسمية على كل عمود في DataFrame.

In [ ]:
data_frame_covid.columns

Index(['country', 'continent', 'date', 'day', 'month', 'year', 'cases',
       'deaths', 'country_code', 'population'],
      dtype='object')

In [ ]:
type(data_frame_covid.columns)

pandas.core.indexes.base.Index

In [ ]:
# Таблица это множество серии, серия это просто один столбец

# Индекс, это номер строки. или колонки  أعمدة - مكبرات الصوت, соответственно колонки

# Можно сказать что датафрейм = таблица

Есть множество способов собрать датафрейм в pandas. от простого pd.DataFrame() до различных классметодов, которые определены для класса dataframe для загрузки данных из разных источников.

Например
from_records() - https://github.com/pandas-dev/pandas/blob/ad178424e2d95badf6caca5f583f3f6053ba4d90/pandas/core/frame.py#L2121
from_dict() - https://github.com/pandas-dev/pandas/blob/ad178424e2d95badf6caca5f583f3f6053ba4d90/pandas/core/frame.py#L1668
read_csv()
read_sql()

--

♣ EXPLAINING ===> https://chat.hix.ai/ar/share/cm0g9bezk01riaj9ssve799u9

Как Series так и DataFrame предоставляют методы для анализа данных, такие как:
- Выборка данных: можно указать особые строки и колонки с которыми вы будете работать, используя индексы,слайсы,условия
- Очистка данных: можно заполнять пропущенные данные, удалять записи в которых не хватает данных.
- Преобразование данных: можно применять функции по всей длинне фрейма или по его отдельным частям
- Аггрегация данных:  можно вычислять такие оценочные величины как сумма, среднее, количество.А также группировать данные по своим критериям при помощи groupby.
- Сортировка: можно упорядочить данные основываясь на значениях в колонках, а также по своим критериям
- Функциональность временных рядов: вы можете работать с данными временных рядов, пересчитывать данные с разной частотой и выполнять вычисления с использованием скользящего окна в DataFrame или Series.

In [ ]:
# Выборка

data_frame_covid[10:15]    # выбирает строки по индексу

,country,continent,date,day,month,year,cases,deaths,country_code,population
10,Australia,Oceania,2020-04-12,12,4,2020,51,3,AUS,24992369.0
11,Austria,Europe,2020-04-12,12,4,2020,247,18,AUT,8847037.0
12,Azerbaijan,Europe,2020-04-12,12,4,2020,67,1,AZE,9942334.0
13,Bahamas,America,2020-04-12,12,4,2020,4,0,BHS,385640.0
14,Bahrain,Asia,2020-04-12,12,4,2020,42,0,BHR,1569439.0

In [ ]:
# data_frame_covid.head() #if don't give it an argument, it's will be display only first 5 lines
data_frame_covid.head(10)  # head(): تُظهر الصفوف الأولى (الافتراضي 5)

,country,continent,date,day,month,year,cases,deaths,country_code,population
0,Afghanistan,Asia,2020-04-12,12,4,2020,34,3,AFG,37172386.0
1,Albania,Europe,2020-04-12,12,4,2020,17,0,ALB,2866376.0
2,Algeria,Africa,2020-04-12,12,4,2020,64,19,DZA,42228429.0
3,Andorra,Europe,2020-04-12,12,4,2020,21,2,AND,77006.0
4,Angola,Africa,2020-04-12,12,4,2020,0,0,AGO,30809762.0
5,Anguilla,America,2020-04-12,12,4,2020,0,0,NaN,NaN
6,Antigua_and_Barbuda,America,2020-04-12,12,4,2020,0,0,ATG,96286.0
7,Argentina,America,2020-04-12,12,4,2020,162,7,ARG,44494502.0
8,Armenia,Europe,2020-04-12,12,4,2020,30,2,ARM,2951776.0
9,Aruba,America,2020-04-12,12,4,2020,6,0,ABW,105845.0

In [ ]:
# data_frame_covid.tail() #if don't give it an argument, it's will be display only last 5 lines
data_frame_covid.tail(10)  # tail(): تُظهر الصفوف الأخيرة (الافتراضي 5)

,country,continent,date,day,month,year,cases,deaths,country_code,population
196,United_Republic_of_Tanzania,Africa,2020-04-12,12,4,2020,0,0,TZA,56318348.0
197,United_States_Virgin_Islands,America,2020-04-12,12,4,2020,1,0,VIR,106977.0
198,United_States_of_America,America,2020-04-12,12,4,2020,28391,1831,USA,327167434.0
199,Uruguay,America,2020-04-12,12,4,2020,7,0,URY,3449299.0
200,Uzbekistan,Asia,2020-04-12,12,4,2020,172,1,UZB,32955400.0
201,Venezuela,America,2020-04-12,12,4,2020,0,0,VEN,28870195.0
202,Vietnam,Asia,2020-04-12,12,4,2020,4,0,VNM,95540395.0
203,Yemen,Asia,2020-04-12,12,4,2020,0,0,YEM,28498687.0
204,Zambia,Africa,2020-04-12,12,4,2020,0,0,ZMB,17351822.0
205,Zimbabwe,Africa,2020-04-12,12,4,2020,3,0,ZWE,14439018.0

In [ ]:
data_frame_covid.iloc[:5]    # # на основе индексов - конец невключаются

# https://chat.hix.ai/ar/share/cm0glw0fs02tbsrrzmflqe6go

,country,continent,date,day,month,year,cases,deaths,country_code,population
0,Afghanistan,Asia,2020-04-12,12,4,2020,34,3,AFG,37172386.0
1,Albania,Europe,2020-04-12,12,4,2020,17,0,ALB,2866376.0
2,Algeria,Africa,2020-04-12,12,4,2020,64,19,DZA,42228429.0
3,Andorra,Europe,2020-04-12,12,4,2020,21,2,AND,77006.0
4,Angola,Africa,2020-04-12,12,4,2020,0,0,AGO,30809762.0

In [ ]:
data_frame_covid[:5]    #the functoin here is just []

,country,continent,date,day,month,year,cases,deaths,country_code,population
0,Afghanistan,Asia,2020-04-12,12,4,2020,34,3,AFG,37172386.0
1,Albania,Europe,2020-04-12,12,4,2020,17,0,ALB,2866376.0
2,Algeria,Africa,2020-04-12,12,4,2020,64,19,DZA,42228429.0
3,Andorra,Europe,2020-04-12,12,4,2020,21,2,AND,77006.0
4,Angola,Africa,2020-04-12,12,4,2020,0,0,AGO,30809762.0

In [ ]:
data_frame_covid.loc[:5]    # на основе индексов - начало и конец включаются

,country,continent,date,day,month,year,cases,deaths,country_code,population
0,Afghanistan,Asia,2020-04-12,12,4,2020,34,3,AFG,37172386.0
1,Albania,Europe,2020-04-12,12,4,2020,17,0,ALB,2866376.0
2,Algeria,Africa,2020-04-12,12,4,2020,64,19,DZA,42228429.0
3,Andorra,Europe,2020-04-12,12,4,2020,21,2,AND,77006.0
4,Angola,Africa,2020-04-12,12,4,2020,0,0,AGO,30809762.0
5,Anguilla,America,2020-04-12,12,4,2020,0,0,NaN,NaN

In [ ]:
###♣ ما هو الفرق بين iloc and loc
# https://chat.hix.ai/ar/share/cm0gm7437030tsrrz2tm9s6o1

In [ ]:
# Как запоминать чтобы не путаться iloc и loc :

# loc - loc по индексам, a индекс это label, поэтому Loc = Label = index... L..L
# iloc - по позициям

### типы данных
В качестве основных типов данных для работы, pandas использует типы данных из NumPy по пораву наследования عن طريق الميراث
https://pandas.pydata.org/pandas-docs/stable/reference/arrays.html

В основном, конечно, можно по смыслу типы данных в любом датафрейме разделить на категориальные и численные الفئوية والعددية.

In [ ]:
# dtypes = to know the type // info = also we can use it to know the type

In [ ]:
data_frame_covid.dtypes

country          object
continent        object
date             object
day               int64
month             int64
year              int64
cases             int64
deaths            int64
country_code     object
population      float64
dtype: object

In [ ]:
data_frame_covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       206 non-null    object
 1   continent     206 non-null    object
 2   date          206 non-null    object
 3   day           206 non-null    int64
 4   month         206 non-null    int64
 5   year          206 non-null    int64
 6   cases         206 non-null    int64
 7   deaths        206 non-null    int64
 8   country_code  202 non-null    object
 9   population    202 non-null    float64
dtypes: float64(1), int64(5), object(4)
memory usage: 16.2+ KB

### Индексирование
Во многом успех работы с данными зависит в скорости доступа к данным и возможности быстро отфильтровать ненужное. Для ускорения работы нам могут помочь индексы. При создании датафрейма у него имеется стандартный индекс для быстрого доступа через него до строк данных. Выбирать такие строки можно с помощью функций .loc() и .iloc() (i==integer). Для датафрейма можно установить новый индекс (при этом либо заменив старый либо создав новый датафрейм из существующего с новым индексом.

الفهرسة:  من نواحٍ عديدة، يعتمد نجاح العمل مع البيانات على سرعة الوصول إلى البيانات والقدرة على تصفية ما هو غير ضروري بسرعة. يمكن أن تساعدنا الفهارس في تسريع عملنا. عندما تقوم بإنشاء إطار بيانات، فإنه يحتوي على فهرس قياسي للوصول بسرعة إلى صفوف البيانات من خلاله. يمكنك تحديد هذه الصفوف باستخدام الوظائف

.loc() و .iloc() (i==عدد صحيح).

 يمكنك تثبيت فهرس جديد لإطار بيانات (إما عن طريق استبدال الفهرس القديم أو إنشاء إطار بيانات جديد من إطار بيانات موجود بفهرس جديد.

In [ ]:
data_frame_covid.head() #here we displayed first 5 lines

,country,continent,date,day,month,year,cases,deaths,country_code,population
0,Afghanistan,Asia,2020-04-12,12,4,2020,34,3,AFG,37172386.0
1,Albania,Europe,2020-04-12,12,4,2020,17,0,ALB,2866376.0
2,Algeria,Africa,2020-04-12,12,4,2020,64,19,DZA,42228429.0
3,Andorra,Europe,2020-04-12,12,4,2020,21,2,AND,77006.0
4,Angola,Africa,2020-04-12,12,4,2020,0,0,AGO,30809762.0

In [ ]:
data_frame_covid.set_index('cases', inplace=True)   #we replaced 'cases' insted of 'indexes'

# https://chat.hix.ai/ar/share/cm0gortwt04k814d8omqyfaof

In [ ]:
data_frame_covid.head()  #display the result again, and we see that the cases insted of indexes

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0

In [ ]:
data_frame_covid.loc[4]  #and here we using loc to display 4 instead of indexes or lables(which is cases here)

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
4,Bahamas,America,2020-04-12,12,4,2020,0,BHS,385640.0
4,Ethiopia,Africa,2020-04-12,12,4,2020,1,ETH,109224559.0
4,Jamaica,America,2020-04-12,12,4,2020,0,JAM,2934855.0
4,Sudan,Africa,2020-04-12,12,4,2020,0,SDN,41801533.0
4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0

In [ ]:
data_frame_covid.iloc[5:10]   #and here using iloc we display lines of cases from 5 to 10

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
0,Anguilla,America,2020-04-12,12,4,2020,0,NaN,NaN
0,Antigua_and_Barbuda,America,2020-04-12,12,4,2020,0,ATG,96286.0
162,Argentina,America,2020-04-12,12,4,2020,7,ARG,44494502.0
30,Armenia,Europe,2020-04-12,12,4,2020,2,ARM,2951776.0
6,Aruba,America,2020-04-12,12,4,2020,0,ABW,105845.0

In [ ]:
data_frame_covid.iloc[4:10, :4]   #[first_line:last_line, :coloums(from right to left)]

                   country continent        date  day
cases
0                   Angola    Africa  2020-04-12   12
0                 Anguilla   America  2020-04-12   12
0      Antigua_and_Barbuda   America  2020-04-12   12
162              Argentina   America  2020-04-12   12
30                 Armenia    Europe  2020-04-12   12
6                    Aruba   America  2020-04-12   12

In [ ]:
data_frame_covid.at[4, 'continent']

# https://chat.hix.ai/ar/share/cm0hydcok0vb6efd1ft1b9br8
# https://chat.hix.ai/ar/share/cm0hyg70w0w9z14d8c4zt5upj

cases
4    America
4     Africa
4    America
4     Africa
4       Asia
Name: continent, dtype: object

In [ ]:
data_frame_covid.loc[[4, 5]] #display rows with values 4 and 5

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
4,Bahamas,America,2020-04-12,12,4,2020,0,BHS,385640.0
4,Ethiopia,Africa,2020-04-12,12,4,2020,1,ETH,109224559.0
4,Jamaica,America,2020-04-12,12,4,2020,0,JAM,2934855.0
4,Sudan,Africa,2020-04-12,12,4,2020,0,SDN,41801533.0
4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0
5,Gambia,Africa,2020-04-12,12,4,2020,0,GMB,2280102.0
5,Guyana,America,2020-04-12,12,4,2020,0,GUY,779004.0
5,Taiwan,Asia,2020-04-12,12,4,2020,1,TWN,23780452.0

### .query(), .where()

фильтрация данных

для того чтобы выбрать несколько условий для фильтрации датафрейма можно воспользоваться методом query(), он позволяет в одну строку записать все условия фильтрации которые вам могут быть нужны при выборе данных. при этом в результате вы получите новый фрейм с данными.

In [ ]:
data_frame_covid.query("cases > 5")    #display rows with values greater than 5, the resul will be a new DataFrame

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0
21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
162,Argentina,America,2020-04-12,12,4,2020,7,ARG,44494502.0
...,...,...,...,...,...,...,...,...,...
376,United_Arab_Emirates,Asia,2020-04-12,12,4,2020,4,ARE,9630959.0
8719,United_Kingdom,Europe,2020-04-12,12,4,2020,839,GBR,66488991.0
28391,United_States_of_America,America,2020-04-12,12,4,2020,1831,USA,327167434.0
7,Uruguay,America,2020-04-12,12,4,2020,0,URY,3449299.0
172,Uzbekistan,Asia,2020-04-12,12,4,2020,1,UZB,32955400.0

In [ ]:
# displayed 114 rows with values > 5

In [ ]:
data_frame_covid.query("cases < 5")

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0
0,Anguilla,America,2020-04-12,12,4,2020,0,NaN,NaN
0,Antigua_and_Barbuda,America,2020-04-12,12,4,2020,0,ATG,96286.0
4,Bahamas,America,2020-04-12,12,4,2020,0,BHS,385640.0
1,Barbados,America,2020-04-12,12,4,2020,0,BRB,286641.0
...,...,...,...,...,...,...,...,...,...
0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0
4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0
0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0
0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0
3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0

In [ ]:
data_frame_covid.query("cases > 5 & deaths == 1")

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
67,Azerbaijan,Europe,2020-04-12,12,4,2020,1,AZE,9942334.0
36,Burkina_Faso,Africa,2020-04-12,12,4,2020,1,BFA,19751535.0
17,Cameroon,Africa,2020-04-12,12,4,2020,1,CMR,25216237.0
53,Cote_dIvoire,Africa,2020-04-12,12,4,2020,1,CIV,25069229.0
56,Cuba,America,2020-04-12,12,4,2020,1,CUB,11338138.0
37,Djibouti,Africa,2020-04-12,12,4,2020,1,DJI,958920.0
136,Finland,Europe,2020-04-12,12,4,2020,1,FIN,5518050.0
14,Iceland,Europe,2020-04-12,12,4,2020,1,ISL,353574.0
18,Latvia,Europe,2020-04-12,12,4,2020,1,LVA,1926542.0
11,Liberia,Africa,2020-04-12,12,4,2020,1,LBR,4818977.0
13,Malta,Europe,2020-04-12,12,4,2020,1,MLT,483530.0
122,Moldova,Europe,2020-04-12,12,4,2020,1,MDA,3545883.0
12,San_Marino,Europe,2020-04-12,12,4,2020,1,SMR,33785.0
25,South_Africa,Africa,2020-04-12,12,4,2020,1,ZAF,57779622.0
172,Uzbekistan,Asia,2020-04-12,12,4,2020,1,UZB,32955400.0

In [ ]:
data_frame_covid.query("~(cases > 5 & deaths == 1)")    #تيلدا تنطي عكس الشرط الموجود بين القوسين

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0
21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0
...,...,...,...,...,...,...,...,...,...
0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0
4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0
0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0
0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0
3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0

In [ ]:
data_frame_covid.query("cases > 5 & continent != 'Africa' ")

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
162,Argentina,America,2020-04-12,12,4,2020,7,ARG,44494502.0
30,Armenia,Europe,2020-04-12,12,4,2020,2,ARM,2951776.0
...,...,...,...,...,...,...,...,...,...
376,United_Arab_Emirates,Asia,2020-04-12,12,4,2020,4,ARE,9630959.0
8719,United_Kingdom,Europe,2020-04-12,12,4,2020,839,GBR,66488991.0
28391,United_States_of_America,America,2020-04-12,12,4,2020,1831,USA,327167434.0
7,Uruguay,America,2020-04-12,12,4,2020,0,URY,3449299.0
172,Uzbekistan,Asia,2020-04-12,12,4,2020,1,UZB,32955400.0

In [ ]:
data_frame_covid.query("cases > 5 & (continent != 'Africa' | deaths < 5) ")   # знак | обозначает логический оператор ИЛИ (OR)

,country,continent,date,day,month,year,deaths,country_code,population
cases,,,,,,,,,
34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
162,Argentina,America,2020-04-12,12,4,2020,7,ARG,44494502.0
30,Armenia,Europe,2020-04-12,12,4,2020,2,ARM,2951776.0
...,...,...,...,...,...,...,...,...,...
376,United_Arab_Emirates,Asia,2020-04-12,12,4,2020,4,ARE,9630959.0
8719,United_Kingdom,Europe,2020-04-12,12,4,2020,839,GBR,66488991.0
28391,United_States_of_America,America,2020-04-12,12,4,2020,1831,USA,327167434.0
7,Uruguay,America,2020-04-12,12,4,2020,0,URY,3449299.0
172,Uzbekistan,Asia,2020-04-12,12,4,2020,1,UZB,32955400.0

.reset_index()

In [ ]:
data_frame_covid = data_frame_covid.reset_index()

In [ ]:
data_frame_covid

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0
...,...,...,...,...,...,...,...,...,...,...
201,0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0
202,4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0
203,0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0
204,0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0

   "Boolean Indexing" (الفهرسة البوليانية) булевская индексация

   وهنا شرح بالشات

  https://chat.hix.ai/ar/share/cm0hz8ybz0vn9efd19dh0dbhj

In [ ]:
data_frame_covid.cases > 5

0       True
1       True
2       True
3       True
4      False
       ...
201    False
202    False
203    False
204    False
205    False
Name: cases, Length: 206, dtype: bool

In [ ]:
data_frame_covid['cases'] > 5  #we can do it this way too

0       True
1       True
2       True
3       True
4      False
       ...
201    False
202    False
203    False
204    False
205    False
Name: cases, Length: 206, dtype: bool

In [ ]:
data_frame_covid[data_frame_covid['cases'] > 5]

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
7,162,Argentina,America,2020-04-12,12,4,2020,7,ARG,44494502.0
...,...,...,...,...,...,...,...,...,...,...
194,376,United_Arab_Emirates,Asia,2020-04-12,12,4,2020,4,ARE,9630959.0
195,8719,United_Kingdom,Europe,2020-04-12,12,4,2020,839,GBR,66488991.0
198,28391,United_States_of_America,America,2020-04-12,12,4,2020,1831,USA,327167434.0
199,7,Uruguay,America,2020-04-12,12,4,2020,0,URY,3449299.0
200,172,Uzbekistan,Asia,2020-04-12,12,4,2020,1,UZB,32955400.0

In [ ]:
data_frame_covid[(data_frame_covid['cases'] > 5) & (data_frame_covid['deaths'] == 3)]

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
10,51,Australia,Oceania,2020-04-12,12,4,2020,3,AUS,24992369.0
15,58,Bangladesh,Asia,2020-04-12,12,4,2020,3,BGD,161356039.0
30,26,Bulgaria,Europe,2020-04-12,12,4,2020,3,BGR,7024216.0
77,70,Greece,Europe,2020-04-12,12,4,2020,3,GRC,10727668.0
118,184,Malaysia,Asia,2020-04-12,12,4,2020,3,MYS,31528585.0
140,13,Nigeria,Africa,2020-04-12,12,4,2020,3,NGA,195874740.0
154,63,Puerto_Rico,America,2020-04-12,12,4,2020,3,PRI,3195153.0
166,275,Serbia,Europe,2020-04-12,12,4,2020,3,SRB,6982084.0
185,33,Thailand,Asia,2020-04-12,12,4,2020,3,THA,69428524.0
189,14,Tunisia,Africa,2020-04-12,12,4,2020,3,TUN,11565204.0

.where()

In [ ]:
# where - для каждого значения, где условие = тру, сохраняет исходное значение, иначе Nan

data_frame_covid.where(data_frame_covid.cases > 5)

# data_frame_covid.where(data_frame_covid.cases > 5, other=0)  #هذا السطر يقوم بنفس العملية، ولكن بدلاً من استبدال القيم غير المطابقة بـ NaN، فإنه يستبدلها بالقيمة 0.

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34.0,Afghanistan,Asia,2020-04-12,12.0,4.0,2020.0,3.0,AFG,37172386.0
1,17.0,Albania,Europe,2020-04-12,12.0,4.0,2020.0,0.0,ALB,2866376.0
2,64.0,Algeria,Africa,2020-04-12,12.0,4.0,2020.0,19.0,DZA,42228429.0
3,21.0,Andorra,Europe,2020-04-12,12.0,4.0,2020.0,2.0,AND,77006.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data_frame_covid     #we didn't change anything

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0
...,...,...,...,...,...,...,...,...,...,...
201,0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0
202,4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0
203,0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0
204,0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0

In [ ]:
filter1 = data_frame_covid.cases > 5
filter2 = data_frame_covid.continent != "Europe"

data_frame_covid.where(filter1 & filter2).dropna()    #dropna delete rows with NaN values, without dropna the result will be 206 rows

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34.0,Afghanistan,Asia,2020-04-12,12.0,4.0,2020.0,3.0,AFG,37172386.0
2,64.0,Algeria,Africa,2020-04-12,12.0,4.0,2020.0,19.0,DZA,42228429.0
7,162.0,Argentina,America,2020-04-12,12.0,4.0,2020.0,7.0,ARG,44494502.0
9,6.0,Aruba,America,2020-04-12,12.0,4.0,2020.0,0.0,ABW,105845.0
10,51.0,Australia,Oceania,2020-04-12,12.0,4.0,2020.0,3.0,AUS,24992369.0
...,...,...,...,...,...,...,...,...,...,...
190,5138.0,Turkey,Asia,2020-04-12,12.0,4.0,2020.0,95.0,TUR,82319724.0
194,376.0,United_Arab_Emirates,Asia,2020-04-12,12.0,4.0,2020.0,4.0,ARE,9630959.0
198,28391.0,United_States_of_America,America,2020-04-12,12.0,4.0,2020.0,1831.0,USA,327167434.0
199,7.0,Uruguay,America,2020-04-12,12.0,4.0,2020.0,0.0,URY,3449299.0
200,172.0,Uzbekistan,Asia,2020-04-12,12.0,4.0,2020.0,1.0,UZB,32955400.0

In [ ]:
df_temp = data_frame_covid.where(filter1 & filter2)
df_temp

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34.0,Afghanistan,Asia,2020-04-12,12.0,4.0,2020.0,3.0,AFG,37172386.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64.0,Algeria,Africa,2020-04-12,12.0,4.0,2020.0,19.0,DZA,42228429.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

.reset_index()

In [ ]:
df_temp.dropna().reset_index()

# هنا راح يبقى عامود الأيندكس الأصلي ويظهر اسمه إيندكس ويبقى لكل صف إيندكسه الاصلي وراح يصير فرغ بين إيندكسات بعض الصفوف لأن اكو صفوف انحذفن بسبب الدروبنا
#  وينضاف عامود بالبدايه بدون اسم بيه إيندكسات بالترتيب للصفوف من الصفر ولحد آخر صف

,index,cases,country,continent,date,day,month,year,deaths,country_code,population
0,0,34.0,Afghanistan,Asia,2020-04-12,12.0,4.0,2020.0,3.0,AFG,37172386.0
1,2,64.0,Algeria,Africa,2020-04-12,12.0,4.0,2020.0,19.0,DZA,42228429.0
2,7,162.0,Argentina,America,2020-04-12,12.0,4.0,2020.0,7.0,ARG,44494502.0
3,9,6.0,Aruba,America,2020-04-12,12.0,4.0,2020.0,0.0,ABW,105845.0
4,10,51.0,Australia,Oceania,2020-04-12,12.0,4.0,2020.0,3.0,AUS,24992369.0
...,...,...,...,...,...,...,...,...,...,...,...
61,190,5138.0,Turkey,Asia,2020-04-12,12.0,4.0,2020.0,95.0,TUR,82319724.0
62,194,376.0,United_Arab_Emirates,Asia,2020-04-12,12.0,4.0,2020.0,4.0,ARE,9630959.0
63,198,28391.0,United_States_of_America,America,2020-04-12,12.0,4.0,2020.0,1831.0,USA,327167434.0
64,199,7.0,Uruguay,America,2020-04-12,12.0,4.0,2020.0,0.0,URY,3449299.0
65,200,172.0,Uzbekistan,Asia,2020-04-12,12.0,4.0,2020.0,1.0,UZB,32955400.0

In [ ]:
df_temp

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34.0,Afghanistan,Asia,2020-04-12,12.0,4.0,2020.0,3.0,AFG,37172386.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64.0,Algeria,Africa,2020-04-12,12.0,4.0,2020.0,19.0,DZA,42228429.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
type(filter1)       #series

pandas.core.series.Series

In [ ]:
filter1

0       True
1       True
2       True
3       True
4      False
       ...
201    False
202    False
203    False
204    False
205    False
Name: cases, Length: 206, dtype: bool

In [ ]:
data_frame_covid.cases > 5

0       True
1       True
2       True
3       True
4      False
       ...
201    False
202    False
203    False
204    False
205    False
Name: cases, Length: 206, dtype: bool

In [ ]:
data_frame_covid.info()                    #also display the type and other info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cases         206 non-null    int64
 1   country       206 non-null    object
 2   continent     206 non-null    object
 3   date          206 non-null    object
 4   day           206 non-null    int64
 5   month         206 non-null    int64
 6   year          206 non-null    int64
 7   deaths        206 non-null    int64
 8   country_code  202 non-null    object
 9   population    202 non-null    float64
dtypes: float64(1), int64(5), object(4)
memory usage: 16.2+ KB

 .apply()

У pandas есть механизмы для применения функций по всему датафрейму или по некоторой его части.

In [ ]:
data_frame_covid

,cases,country,continent,date,day,month,year,deaths,country_code,population
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0
...,...,...,...,...,...,...,...,...,...,...
201,0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0
202,4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0
203,0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0
204,0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0

In [ ]:
data_frame_covid['population_mln']   #error, because this column is not exist

KeyError: 'population_mln'

apply = تطبيق

In [ ]:
# apply = تطبيق
# هي مجرد ادكول طبق اللي بين القوسين

# https://chat.hix.ai/ar/share/cm0i0fvvv0xa72tfemvdr17yl

In [ ]:
data_frame_covid['population_mln'] = data_frame_covid['population'].apply(lambda x: x / 1_000_000)   # lambda ==> https://chat.hix.ai/ar/share/cm0i454rt0zbf6y4pm5whxbrs
data_frame_covid

#see that columns population and population_mln are the same

,cases,country,continent,date,day,month,year,deaths,country_code,population,population_mln
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0,37.172386
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0,2.866376
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0,42.228429
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0,0.077006
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0,30.809762
...,...,...,...,...,...,...,...,...,...,...,...
201,0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0,28.870195
202,4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0,95.540395
203,0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0,28.498687
204,0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0,17.351822
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0,14.439018

In [ ]:
s = '2024-10-20'
s.split('-')            # split ==> https://chat.hix.ai/ar/share/cm0i4ns580zlp14d89xevki2s
# print(s.split('-'))
print(s.split('-')[0])

# x.split('-'): تقوم هذه الدالة بتقسيم السلسلة x إلى قائمة باستخدام الشرطة '-' كفاصل. على سبيل المثال، إذا كانت x هي '2023-10-05'، ستكون النتيجة ['2023', '10', '05'].
# [0]: هذا الجزء يصل إلى العنصر الأول من القائمة الناتجة، والذي يمثل السنة. لذا، بالنسبة للتاريخ '2023-10-05'، ستعيد الدالة '2023'

2024

In [ ]:
data_frame_covid['year_new'] = data_frame_covid['date'].apply(lambda x: x.split('-')[0])
data_frame_covid

,cases,country,continent,date,day,month,year,deaths,country_code,population,population_mln,year_new
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0,37.172386,2020
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0,2.866376,2020
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0,42.228429,2020
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0,0.077006,2020
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0,30.809762,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
201,0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0,28.870195,2020
202,4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0,95.540395,2020
203,0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0,28.498687,2020
204,0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0,17.351822,2020
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0,14.439018,2020

In [ ]:
data_frame_covid[["cases"]]   #to dispaly specific column, we use [[""]]

     cases
0       34
1       17
2       64
3       21
4        0
..     ...
201      0
202      4
203      0
204      0
205      3

[206 rows x 1 columns]

In [ ]:
type(data_frame_covid[["cases"]])        #the type is DataFrame

pandas.core.frame.DataFrame

In [ ]:
data_frame_covid["cases"]   #we can use only one [] if we need to display only one column, and the type will be series


# Series одномерный массив
# DataFrame может быть одномерный и двумерный массив

0      34
1      17
2      64
3      21
4       0
       ..
201     0
202     4
203     0
204     0
205     3
Name: cases, Length: 206, dtype: int64

In [ ]:
type(data_frame_covid["cases"])

pandas.core.series.Series

In [ ]:
data_frame_covid[["cases", "deaths"]]

     cases  deaths
0       34       3
1       17       0
2       64      19
3       21       2
4        0       0
..     ...     ...
201      0       0
202      4       0
203      0       0
204      0       0
205      3       0

[206 rows x 2 columns]

In [ ]:
data_frame_covid["cases", "deaths"]     #error, because two columns are data_frame(must be with [two]), not a series

KeyError: ('cases', 'deaths')

In [ ]:
# data_frame_covid[["cases", "deaths"]]

In [ ]:
data_frame_covid["cases_deaths_rate"] = data_frame_covid[["cases", "deaths"]].apply(lambda x: x["deaths"]/x["cases"] if x["deaths"] and x["cases"] else 0, axis=1)
data_frame_covid[["cases", "deaths"]].T.apply(lambda x: x["deaths"]/x["cases"] if x["deaths"] and x["cases"] else 0)

# https://chat.hix.ai/ar/share/cm0i79rsk117z6y4p4fpsvvt8

0      0.088235
1      0.000000
2      0.296875
3      0.095238
4      0.000000
         ...
201    0.000000
202    0.000000
203    0.000000
204    0.000000
205    0.000000
Length: 206, dtype: float64

In [ ]:
data_frame_covid["cases_deaths_rate"] = data_frame_covid[["cases", "deaths"]].apply(lambda x: x["deaths"]/x["cases"] if x["deaths"] and x["cases"] else 0) #error, because columns, should be rows
data_frame_covid[["cases", "deaths"]].T.apply(lambda x: x["deaths"]/x["cases"] if x["deaths"] and x["cases"] else 0)

# خطأ لأنو هيجي ياخذ اعمده مو صفوف
# بشكل افتراضي، تعمل .apply() على الأعمدة (axis=0)

KeyError: 'deaths'

In [ ]:
data_frame_covid[["cases", "deaths"]].T      #we added .T and conveted columns to rows, look at the result below ==> 2 rows*206 columns

# .T ==> https://chat.hix.ai/ar/share/cm0i5o4uo0z8yefd1pphbc2fp

,0,1,2,3,4,5,6,7,8,9,...,196,197,198,199,200,201,202,203,204,205
cases,34,17,64,21,0,0,0,162,30,6,...,0,1,28391,7,172,0,4,0,0,3
deaths,3,0,19,2,0,0,0,7,2,0,...,0,0,1831,0,1,0,0,0,0,0

In [ ]:
data_frame_covid[["cases", "deaths"]].T.apply(lambda x: x["deaths"]/x["cases"] if x["deaths"] and x["cases"] else 0)

0      0.088235
1      0.000000
2      0.296875
3      0.095238
4      0.000000
         ...
201    0.000000
202    0.000000
203    0.000000
204    0.000000
205    0.000000
Length: 206, dtype: float64

In [ ]:
# lambda
# ما هي؟
# lambda هي دالة مجهولة أو غير مسماة (anonymous function) في بايثون. هي طريقة مختصرة لإنشاء دالة بدون الحاجة لتسميتها باستخدام الكلمة المفتاحية def.
# تكون الدوال المجهولة عادة قصيرة جدًا وتحتوي على تعبير واحد فقط. هي مفيدة عندما تحتاج إلى إنشاء دالة صغيرة في مكان واحد للاستخدام لمرة واحدة.

# الصيغه
# lambda arguments: expression

# arguments: هي المتغيرات المدخلة للدالة.
# expression: هو التعبير (expression) الذي سيتم تنفيذه عند استدعاء الدالة.

f = lambda x: x * 2
print(f(5))  # Output: 10

* axis = 0 - строки
* axis = 1 - столбцы

In [ ]:
None / 0       #خطأ لان ما يصير هيجي عمليه

TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

In [ ]:
0 / None        #نفس الشي ما يصير

TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

In [ ]:
data_frame_covid["cases_deaths_rate"] = data_frame_covid[["cases", "deaths"]].apply(lambda x: x["deaths"]/x["cases"] if x["deaths"] and x["cases"] else 0, axis=1)
data_frame_covid #طلعنا نسبة الأموات الى الحالات

,cases,country,continent,date,day,month,year,deaths,country_code,population,population_mln,year_new,cases_deaths_rate
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0,37.172386,2020,0.088235
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0,2.866376,2020,0.000000
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0,42.228429,2020,0.296875
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0,0.077006,2020,0.095238
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0,30.809762,2020,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0,28.870195,2020,0.000000
202,4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0,95.540395,2020,0.000000
203,0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0,28.498687,2020,0.000000
204,0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0,17.351822,2020,0.000000
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0,14.439018,2020,0.000000

In [ ]:
# .sort_values()

In [ ]:
data_frame_covid.sort_values("cases_deaths_rate", ascending=False)     # تصاعدي

,cases,country,continent,date,day,month,year,deaths,country_code,population,population_mln,year_new,cases_deaths_rate
88,1,Honduras,America,2020-04-12,12,4,2020,1,HND,9587522.0,9.587522,2020,1.000000
80,3,Guam,Oceania,2020-04-12,12,4,2020,1,GUM,165768.0,0.165768,2020,0.333333
117,3,Malawi,Africa,2020-04-12,12,4,2020,1,MWI,18143315.0,18.143315,2020,0.333333
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0,42.228429,2020,0.296875
64,4,Ethiopia,Africa,2020-04-12,12,4,2020,1,ETH,109224559.0,109.224559,2020,0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,3,Guinea_Bissau,Africa,2020-04-12,12,4,2020,0,GNB,1874309.0,1.874309,2020,0.000000
85,5,Guyana,America,2020-04-12,12,4,2020,0,GUY,779004.0,0.779004,2020,0.000000
86,2,Haiti,America,2020-04-12,12,4,2020,0,HTI,11123176.0,11.123176,2020,0.000000
87,0,Holy_See,Europe,2020-04-12,12,4,2020,0,VAT,1000.0,0.001000,2020,0.000000
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0,14.439018,2020,0.000000

.drop()

In [ ]:
data_frame_covid.drop('cases_deaths_rate')       #error, because without axis=1 => drop needs axis

KeyError: "['cases_deaths_rate'] not found in axis"

In [ ]:
data_frame_covid = data_frame_covid.drop('cases_deaths_rate', axis=1)
data_frame_covid

,cases,country,continent,date,day,month,year,deaths,country_code,population,population_mln,year_new
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0,37.172386,2020
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0,2.866376,2020
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0,42.228429,2020
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0,0.077006,2020
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0,30.809762,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
201,0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0,28.870195,2020
202,4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0,95.540395,2020
203,0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0,28.498687,2020
204,0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0,17.351822,2020
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0,14.439018,2020

### оценочные операции над датефреймом
عمليات التقييم على إطار زمني

In [ ]:
data_frame_covid.isna()   # https://chat.hix.ai/ar/share/cm0i9i2vr0q9q7jti20zq4ebp

#.isna() returned true if the values are NA and false if not NA.
# NA values, such as None or numpy.NaN. ==> like Null

# isna() создает DataFrame того же размера, где все пропущенные значения (NaN) заменены на True, а остальные на False.

,cases,country,continent,date,day,month,year,deaths,country_code,population,population_mln,year_new
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
201,False,False,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,False,False
205,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
data_frame_covid.isna().sum()

# sum() складывает значения True (которые Python считает за 1) по каждому столбцу, таким образом подсчитывая количество NaN в каждом из них.
# look at the result and see the column country_code have 4 true values

cases             0
country           0
continent         0
date              0
day               0
month             0
year              0
deaths            0
country_code      4
population        4
population_mln    4
year_new          0
dtype: int64

In [ ]:
data_frame_covid['cases'].notna()       #.notna() returned true if the value is't NaN ... and it's DEEEEEEELETE them (NaN values)

0      True
1      True
2      True
3      True
4      True
       ...
201    True
202    True
203    True
204    True
205    True
Name: cases, Length: 206, dtype: bool

In [ ]:
data_frame_covid_dropna = data_frame_covid[data_frame_covid['cases'].notna()]

data_frame_covid_dropna = data_frame_covid_dropna[data_frame_covid_dropna['deaths'].notna()]

data_frame_covid_dropna = data_frame_covid_dropna[data_frame_covid_dropna['population'].notna()]

# explaining the code ==> https://chat.hix.ai/ar/share/cm0ia4izc12o3rqcx3a3hggkq
# examples ==> https://chat.hix.ai/ar/share/cm0iaovtz13ntsrrz3yss308v

In [ ]:
data_frame_covid_dropna

,cases,country,continent,date,day,month,year,deaths,country_code,population,population_mln,year_new
0,34,Afghanistan,Asia,2020-04-12,12,4,2020,3,AFG,37172386.0,37.172386,2020
1,17,Albania,Europe,2020-04-12,12,4,2020,0,ALB,2866376.0,2.866376,2020
2,64,Algeria,Africa,2020-04-12,12,4,2020,19,DZA,42228429.0,42.228429,2020
3,21,Andorra,Europe,2020-04-12,12,4,2020,2,AND,77006.0,0.077006,2020
4,0,Angola,Africa,2020-04-12,12,4,2020,0,AGO,30809762.0,30.809762,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
201,0,Venezuela,America,2020-04-12,12,4,2020,0,VEN,28870195.0,28.870195,2020
202,4,Vietnam,Asia,2020-04-12,12,4,2020,0,VNM,95540395.0,95.540395,2020
203,0,Yemen,Asia,2020-04-12,12,4,2020,0,YEM,28498687.0,28.498687,2020
204,0,Zambia,Africa,2020-04-12,12,4,2020,0,ZMB,17351822.0,17.351822,2020
205,3,Zimbabwe,Africa,2020-04-12,12,4,2020,0,ZWE,14439018.0,14.439018,2020

In [ ]:
data_frame_covid_dropna.isna().sum()

cases             0
country           0
continent         0
date              0
day               0
month             0
year              0
deaths            0
country_code      1
population        0
population_mln    0
year_new          0
dtype: int64

In [ ]:
data_frame_covid_dropna = data_frame_covid_dropna[data_frame_covid_dropna['country_code'].notna()]
data_frame_covid_dropna.isna().sum()

cases             0
country           0
continent         0
date              0
day               0
month             0
year              0
deaths            0
country_code      0
population        0
population_mln    0
year_new          0
dtype: int64

In [ ]:
data_frame_covid_dropna.groupby('continent')['cases'].sum()

# https://chat.hix.ai/ar/share/cm0ifbwm316awsrrznv26xlrv
# https://chat.hix.ai/ar/share/cm0ifcilo16c23g5oqb1vh8x3

continent
Africa       714
America    33519
Asia       12979
Europe     34141
Oceania       68
Name: cases, dtype: int64

In [ ]:
data_frame_covid_dropna.groupby('continent')['cases'].sum().reset_index()    #with index

  continent  cases
0    Africa    714
1   America  33519
2      Asia  12979
3    Europe  34141
4   Oceania     68

In [ ]:
data_frame_covid_dropna.groupby('continent').agg({'cases': 'sum'})     # the same as last code, but using agg
                                                                       # https://chat.hix.ai/ar/share/cm0ifqcxg159kefd17uzarnoj

# data_frame_covid_dropna.groupby('continent').agg({'cases': 'sum'}).reset_index()    #with index

           cases
continent
Africa       714
America    33519
Asia       12979
Europe     34141
Oceania       68

In [ ]:
data_frame_covid_dropna.groupby('continent')[['cases','deaths']].sum()

           cases  deaths
continent
Africa       714      52
America    33519    2111
Asia       12979     383
Europe     34141    3571
Oceania       68       4

In [ ]:
data_frame_covid_dropna.groupby('continent').agg({'cases':'sum', 'deaths':'sum'})

           cases  deaths
continent
Africa       714      52
America    33519    2111
Asia       12979     383
Europe     34141    3571
Oceania       68       4

In [ ]:
import numpy as np

In [ ]:
np.mean(data_frame_covid_dropna["cases"])   #Считаем среднее значение

405.07960199004975

### aggregate operations

In [ ]:
data_frame_covid.agg(maximal_cases=('cases', max))  # https://chat.hix.ai/ar/share/cm0ihqmlh00f3kqh52r6na8fu

<ipython-input-115-a2a2eb5978a5>:1: FutureWarning: The provided callable <built-in function max> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  data_frame_covid.agg(maximal_cases=('cases', max))

               cases
maximal_cases  28391

In [ ]:
data_frame_covid_dropna.agg({'cases': 'max'})

cases    28391
dtype: int64

In [ ]:
data_frame_covid.agg(minimal_cases=('cases', min), maximal_cases=('cases', max))

<ipython-input-117-7f3c31b99320>:1: FutureWarning: The provided callable <built-in function min> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  data_frame_covid.agg(minimal_cases=('cases', min), maximal_cases=('cases', max))
<ipython-input-117-7f3c31b99320>:1: FutureWarning: The provided callable <built-in function max> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  data_frame_covid.agg(minimal_cases=('cases', min), maximal_cases=('cases', max))

               cases
minimal_cases      0
maximal_cases  28391

In [ ]:
data_frame_covid.agg(cases_sum=('cases', sum))

<ipython-input-118-078f77ba74d3>:1: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  data_frame_covid.agg(cases_sum=('cases', sum))

           cases
cases_sum  81421

In [ ]:
data_frame_covid.agg(cases_sum=('cases', lambda x: sum(x)))

           cases
cases_sum  81421

In [ ]:
data_frame_covid.agg(cases_x_2=('cases', lambda x: sum(x*2) ))

            cases
cases_x_2  162842

In [ ]:
data_frame_covid.describe()   # https://chat.hix.ai/ar/share/cm0ihviau16irefd1nm164qdu

,cases,day,month,year,deaths,population,population_mln
count,206.000000,206.000000,206.000000,206.0,206.000000,2.020000e+02,202.000000
mean,395.247573,12.024272,3.985437,2020.0,29.713592,3.731716e+07,37.317164
std,2160.176439,0.424141,0.209020,0.0,159.533131,1.413776e+08,141.377565
min,0.000000,11.000000,1.000000,2020.0,0.000000,1.000000e+03,0.001000
25%,0.000000,12.000000,4.000000,2020.0,0.000000,1.278222e+06,1.278223
50%,11.500000,12.000000,4.000000,2020.0,0.000000,7.042862e+06,7.042861
75%,88.750000,12.000000,4.000000,2020.0,3.000000,2.600084e+07,26.000835
max,28391.000000,18.000000,4.000000,2020.0,1831.000000,1.392730e+09,1392.730000

In [ ]:
data_frame_covid.describe(include='object')

            country continent        date country_code year_new
count           206       206         206          202      206
unique          206         6           3          202        1
top     Afghanistan    Europe  2020-04-12          AFG     2020
freq              1        54         204            1      206

# Summary

Numpy это основополагающая библиотека для анализа данных и алгоритмов машинного обучения на python. Она имеет свои преимущества и свои недостатки относительно стандартной реализации списков в cpython. Для numpy реализованы некоторые методы линейнной алгебры и обраотки сигналов, а в scipy, основанной на numpy реализованы еще и дополнительные алгоритмы по оптимизации и решению дифуров.
При работе с прямоугольными именованными таблицами данных классическим инструментом можно считать pandas. Pandas представляет собой библиотеку предназначенную для обработки датафреймов - именованных прямоугольных таблиц. Эти таблицы состоят из серий данных, колонок и индексов. Последние помогают находить строки в датафрейме. Основными вариантами использования pandas являются обработка, фильтрация, трфнсформирование и очистка данных. В отдельных случаях возможна работа с геопространственными данными через дополнение geopandas, однако геопространственные термины и типы данных скорее являются отдельной темой для лекции.

# Вопросы для самоконтроля

- какие задачи вы бы выполняли с использованием numpy?
- что такое датафрейм?
- в чем отличие dataframe и series?
- как бы вы использовали индекс в pandas?

In [ ]:
# https://chat.hix.ai/ar/share/cm0ihwc5f16jrefd1ovb3lfex

## ДЗ

1. Загрузите данные и выведите первые 10 строк DataFrame - ссылка - https://raw.githubusercontent.com/DataRepo2019/Data-files/master/subset-covid-data.csv.

2. Отфильтруйте строки DataFrame, где количество случаев больше 50.

3. Подсчитайте среднее количество случаев и смертей по каждому континенту.

4. Создайте новый столбец, который будет содержать количество случаев на миллион человек.

5. Замените все отсутствующие значения в столбце `cases` на 0.

6. Отсортируйте DataFrame по количеству случаев в порядке убывания.

7. Выберите только столбцы `country`, `cases` и `deaths`.

8. Сделайте столбец country_code индексом DataFrame

**ФОРМАТ СДАЧИ:** ссылка на колаб + файл с расширением ipynb

#  Дополнительная литература

- "Numerical python. A Practical Techniques Approach for Industry" - Robert Johansson
- "Pandas Basics" - Oswald Campesato - гл. 4-6
- "Learning Pandas" - Matthew Rosch
- "Практическая статистика для специалистов data Science" - Э.Брюс, П.Брюс, П.Гедек